name: LocalServer Build

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Server
        working-directory: local_server
        run: cargo build --release --manifest-path=Cargo.toml
