name: LocalServer Build

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write


env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Server
        run: cargo build --release --manifest-path=local_server/Cargo.toml
